name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 12am UTC
    - cron: "0 0 * * *"

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: lniilisl/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: true
          SHOW_LINES_OF_CODE: true
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_OS: false
          SHOW_PROJECTS: false
          SHOW_LANGUAGE_PER_REPO: true
          SHOW_TIMEZONE: false
          SHOW_LOC_CHART: false
          COMMIT_MESSAGE: Updated the Readme
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
